[project]
name = "laliga-fantasy-builder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "jwt>=1.4.0",
]

[dependency-groups]
dev = [
    "bandit>=1.9.4",
    "black>=26.5.1",
    "mypy>=2.3.1",
    "poethepoet>=0.48.0",
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]
